export { default as Home } from './Home.jsx'
export { default as Orders } from './Orders.jsx'
export { default as Auth } from './Auth.jsx'
export { default as Inventory } from './Inventory.jsx'
export { default as Product } from './Product.jsx'